spring.application.name=PartFinder

# Configuración de Groq (IA)
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama3-8b-8192

# Para evitar que se corte la conexión si la IA tarda
spring.mvc.async.request-timeout=60000